name: Check Trash IDs

on:
  pull_request:

jobs:
  check_trash_ids:
    name: Check Trash IDs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Config Repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Checkout Trash Repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          repository: TRaSH-Guides/Guides
          path: trash

      - name: Check Trash IDs
        run: pwsh ci/CheckInvalidTrashIds.ps1 trash .
