name: Check Dates

on:
  pull_request:

jobs:
  check_dates:
    name: Check Dates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Get Changed Files
        id: files
        uses: tj-actions/changed-files@e0021407031f5be11a464abee9a0776171c79891 # v47.0.1
        with:
          separator: ","

      - name: Check Dates
        shell: pwsh
        run: |
          $files = "${{ steps.files.outputs.all_changed_files }}".Split(',')
          $nowDate = Get-Date -Format "yyyy-MM-dd"
          ci/CheckInvalidDates.ps1 $files $nowDate
