name: Check Trash IDs

on:
  pull_request:

jobs:
  check_trash_ids:
    name: Check Trash IDs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Config Repo
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Checkout Trash Repo
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          repository: TRaSH-Guides/Guides
          path: trash

      - name: Check Trash IDs
        run: pwsh ci/CheckInvalidTrashIds.ps1 trash .
